# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1(self):
    self.driver.get("https://guru.qahacking.ru/")
    self.driver.set_window_size(1920, 982)
    self.driver.find_element(By.CSS_SELECTOR, ".uk-navbar-nav > li:nth-child(1) > a").click()
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("Иван")
    self.driver.find_element(By.ID, "lastName").click()
    self.driver.find_element(By.ID, "lastName").send_keys("Иванов")
    self.driver.find_element(By.ID, "userEmail").click()
    self.driver.find_element(By.ID, "userEmail").send_keys("mail@mail.ru")
    self.driver.find_element(By.ID, "userNumber").click()
    self.driver.find_element(By.ID, "userNumber").send_keys("88008889900")
    self.driver.find_element(By.ID, "date").click()
    self.driver.find_element(By.ID, "date").send_keys("18 Aug")
    self.driver.find_element(By.ID, "currentAddress").click()
    self.driver.find_element(By.ID, "currentAddress").send_keys("sdfdsf")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".uk-section-large").click()
    self.driver.find_element(By.CSS_SELECTOR, ".uk-section-large").click()
    self.driver.find_element(By.ID, "submit").click()
  
